### ISSUE TITLE
Noob can't build an .app file

### ISSUE THREAD

**Issue by mcevzar** [Pyroh/Fluor#1]
##### It's great for my 60%keyboard as I have no Fn row and can't have bought features of Fn keys enabled at the same time.

I don't have an Apple Developer account and for now I run your app through Xcode as a builded Xcode project. 

Is it possible to extract it as .app so I could run it outside of Xcode?

Pardon me for the silly question.

Best of luck :)

Michel Cevzar

**Comment by nantunes** [comment]
You can use the bundled versions available at https://github.com/Pyroh/Fluor/releases.

**Comment by mcevzar** [comment]
Thank you. Sorry was not looking around enough.

**Comment by Pyroh** [comment]
You can also now install via brew cask. I'll update the README during my lunch break.
