### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by furins** [Pyroh/Fluor#11]
Hi Pyroh
it should be mentioned in the README.md that this application requires El Capitain (10.11) or greater.
If I'd have enough time I'll put an eye on the code to see if I'm able to help you and to prepare a PR supporting 10.10 (that is still >20% of the installed MacOS as of Jan 2017).

thank you
Stefano

**Comment by Pyroh** [comment]
I've lowered the requirement to 10.10.
It will be delivered in the next update I will release as soon as possible.

**Comment by furins** [comment]
Thank you!

**Comment by Pyroh** [comment]
Version 1.1 now requires macOS 10.10 instead of 10.11.
