### ISSUE TITLE
Behaviour when multiple users are logged in

### ISSUE THREAD

**Issue by danepod** [Pyroh/Fluor#13]
When logged in to two users, each running an instance of Flour, it seems that the Flour running on the suspended user still controls the Fn keys. You can reproduce it like this:

Log in to a user, start Flour and an app that you set to swap the keys. Now log in to another user while leaving that app open on the suspended user. Now try the Fn keys on user 2. They are now swapped as set by Flour running on user 1.

The intended behaviour should be that these settings are isolated per user, I think. You can't see from user 2 if user 1 has an app running that makes Flour modify the Fn keys.

Keep up the good work, loving it. ❤️
Greetings, Dane

**Comment by Pyroh** [comment]
I'm currently working on the issue.
Thanks for reporting it and thanks for your support 😃

**Comment by Pyroh** [comment]
This should be fixed in the new 1.1 release.
Could you test it please ?

**Comment by danepod** [comment]
Seems to be working fine now. Thanks! :)
