### ISSUE TITLE
Fluor doesn't function when Karabiner-Elements is active

### ISSUE THREAD

**Issue by andrew-kennedy** [Pyroh/Fluor#14]
I believe the culprit here is something from the code you used from fntoggle, and as such may fall outside of your knowledge to fix, but I just wanted to make you aware that as stated in the title, Fluor simply doesn't function unless [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements) is quit. I also opened an issue [there](https://github.com/tekezo/Karabiner-Elements/issues/579) in case @tekezo knows how to fix it.

**Comment by Pyroh** [comment]
Fluor just change the behaviour of the fn keys at the system level. It's a flag that will be used somewhere at a lower level.

What you could try is quitting Fluor and trying to change the option *Use F1, F2, etc. keys as standard function keys* under *Keyboard* in the *System Preferences* and see what happens while using Karabiner-Element.
