### ISSUE TITLE
Why didn't I ever hear of this?

### ISSUE THREAD

**Issue by sn0wyfall** [Pyroh/Fluor#15]
Why have I never heard of this? Where was this when I needed it?

**Comment by Grogs** [comment]
It really would be great to see this coming in google's search results. I think it's just too new and will improve with time. 

Might we worth creating a web page for it? You can use github pages, it can be as simple as putting an index.html in a `gh-pages` branch.

**Comment by Pyroh** [comment]
I'll do it as soon as I find some spare time.
