### ISSUE TITLE
codelite is not detected as running app

### ISSUE THREAD

**Issue by xaljox** [Pyroh/Fluor#17]
I want to use Fluor with the codelite ide to use its keyboard shortcuts. When the application is running, Fluor doesn't see it so it is not possible to set the function keys to function keys when this application is active.

**Comment by Pyroh** [comment]
I've just tried and effectively Codelite doesn't appear in Fluor's app list.
I think I'll have to either contact Codelite's devs or add it to a sort of white list.
It's a matter of the app activation policy that's all I can say.
