### ISSUE TITLE
Minimal Review

### ISSUE THREAD

**Issue by potecuta** [Pyroh/Fluor#2]
The app actually looks nice, but sadly for Xcode it only does two things:
 F11 - show desktop
 F12 - show dashboard

It would be nice if I could set custom actions for different apps. I will keep an eye on it if it gets updated :D

**Comment by SteveEdson** [comment]
@potecuta Different actions should be customisable per application, all this app does is enable you to use the function keys per app, rather than the brightness and media functions.

**Comment by potecuta** [comment]
@SteveEdson Oh, ok. That makes sense :D I will close this issue then. Thanks for the answer!

**Comment by Pyroh** [comment]
Since everything is answered I close this issue.
