### ISSUE TITLE
doesn't work with wireless keyboard

### ISSUE THREAD

**Issue by Henry-E** [Pyroh/Fluor#22]
Hey, I'm using the logitech k380 and it doesn't appear to work with fluor. Is this something that's fundamentally not possible?

**Comment by andyspicer** [comment]
Doesn't seem to be working on the Logitech K480 either. I'm going to try a couple of other keyboard types.

**Comment by Pyroh** [comment]
Sadly I don't and certainly won't support third party keyboards. It would imply to much work, sorry 😕.

**Comment by Henry-E** [comment]
that's no problem, it's already a great application. Just checking in case it was possible
