### ISSUE TITLE
Fluor 1.2beta - cannot start anymore on macos 10.13

### ISSUE THREAD

**Issue by supersophie** [Pyroh/Fluor#30]
Hi,

Just noticed that this app won't run anymore ( cannot recall if this ran or not immediately after the upgrade).  I upgraded from 10.12 to 10.13 last night.  I can click on the app and nothing happens. 

Where can I find the log files?

Thanks.

**Comment by supersophie** [comment]
Ran the binary from the Terminal and the app popped up into the notifications bar.  Weird.

**Comment by Pyroh** [comment]
Since it's a beta no support is offered. The 1.1 version works well on macOS 10.13.
