### ISSUE TITLE
High Sierra support

### ISSUE THREAD

**Issue by markesaaremets** [Pyroh/Fluor#32]
Is it me, or it doesn't seem to work on 10.13.1?

**Comment by Pyroh** [comment]
I'm using Fluor v1.1 on a daily basis on my MBPr running under 10.13.1 and everything is fine appart for #25 issue.
If you can give me more context we perhaps should find a fix.
I need at least mac model and Fluor settings you set.

**Comment by markesaaremets** [comment]
Looks like I got it wrong. Was under impression that it'd work with the Touch Bar.

(My use-case is that I'd like to have Touch Bar actions available on certain apps, having the static function keys on by default. Right now the only option is to use fn key to expose TB-specific stuff)
