### ISSUE TITLE
Different behaviour with external keyboard

### ISSUE THREAD

**Issue by ryanthara** [Pyroh/Fluor#33]
I use an external keyboard on my MBP with highSierra on it and the below shown beta version of Fluor.

<img width="625" alt="issue" src="https://user-images.githubusercontent.com/7117072/35775095-8a7a6dfe-0982-11e8-8bef-afc40088065f.png">

The behaviour of the function keys are remapped correct on the internal keyboard, but not on the external one. 

Internal keyboard without the fn key, external keyboard with fn key.

**Comment by Pyroh** [comment]
Unfortunately external keyboards are not supported by **Fluor** sorry. They probably never will since it is far too much work.

**Comment by Jendker** [comment]
I found nice solution to that.

1. use Karabiner Elements
2. define the new profile with the given application name (for auto-load)
3. define the use of f keys for the given external keyboard (or for all devices)
4. set up auto-load of the profile with https://github.com/nriley/Karabiner-Elements-App-Profiles/releases (the more detailed info in the README in zip file)

In 10 minutes it's up and running :)
