### ISSUE TITLE
Brew Cask support

### ISSUE THREAD

**Issue by SteveEdson** [Pyroh/Fluor#4]
First of all, thank you for this, I never realised I needed this app until now.

Support for installing via `brew cask` would be great https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md.

**Comment by Pyroh** [comment]
Already done. I just added the information in the README file. (tip: `brew cask install fluor`)

**Comment by SteveEdson** [comment]
Just noticed, thanks 👍
