### ISSUE TITLE
Crashes upon launch

### ISSUE THREAD

**Issue by huyz** [Pyroh/Fluor#40]
The app crashes on me on Mac OS X 10.11.6 (El Capitan).

Nothing useful in the Console:

```
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```

Is this app not supported on 10.11?

**Comment by faxotherapy** [comment]
the app. doesn't launch on my side. Clicking twice on the app. icon produces nothing. Ran on OS 10.11.6
