### ISSUE TITLE
Fluor on external keyboards

### ISSUE THREAD

**Issue by Jendker** [Pyroh/Fluor#43]
I know that there would be a lot of work to allow the functionality for external keyboards and this is why it wasn't done yet, but why not to cope it with the script which will change the standard f key functionality in MacOS Preferences? Something like the thing done here: https://github.com/jakubroztocil/macos-fn-toggle
This could make it work with external keyboards with small effort. 

What do you think about it? I could also help with that (even though I didn't program with Swift yet).

**Comment by Pyroh** [comment]
Hello,

Since Fluor is based on fn-toggle I don't think it could be a solution.
External keyboard support may come later. (remember that I used _may_, not _will_ 😉).

Regards.

**Comment by berezovskyi** [comment]
Fluor works for me on Apple Bluetooth keyboard with Karabiner Elements and Fluor.

**Comment by Jendker** [comment]
Thanks for the hint! It works like a charm now :) I can move some functionality from Karabiner to Fluor.
