### ISSUE TITLE
Slow reaction to apps focus switching

### ISSUE THREAD

**Issue by Den-Rimus** [Pyroh/Fluor#44]
There's an issue, that reproduces often enough to considerable, I think.

App does react on desktop apps being switched, but it happens after some time (several seconds). This might cause confusion and undesired results. Example: I have Fn keys set up for my IDE and media buttons for everything else. I use some applications, then switch to IDE and want to skip song. Pressing fn + F9 (I am in IDE already and I know that media keys here work with fn key only), but system still thinks media keys are in priority so I get F9 pressed instead. In different IDE's this might be set to different actions, e.g. start building project 😂  which is something I don't want.

Can something be done about this? Palua did not have this behaviour, but it is not available anymore.

I use latest Fluor 2.0.2 build1289 with MacOS 10.14.1

**Comment by Pyroh** [comment]
Hello,

Can you please tell me which is the said IDE, please ?

Regards

**Comment by Den-Rimus** [comment]
Yes - it is AndroidStudio, based on IntelliJ IDEA

**Comment by onezhaoyn** [comment]
i'm having the same issue, my IDE is VS Code
