### ISSUE TITLE
Error? with F11

### ISSUE THREAD

**Issue by hvt2** [Pyroh/Fluor#48]
Flour 2.1.0
Mac mojave

I switch mode to fn on TexStudio. Press F11 and it calls the default function of mac: show desktop, instead of another shortcut key I assigned in TexStudio.
I tried to get the source and fix but figured out that they are outdated.
Could you fix this for us or release the source so I can try?

Bests,

**Comment by Pyroh** [comment]
Hello,

It has nothing to do with Fluor but it's an OS matter. By default macOS sets the *Show Desktop* shortcut on the F11 key. All you have to do is to first go to *System Preferences > Keyboard*. Then on the *Shortcuts* tab, under the *Mission Control* category un-check the *Show Desktop* entry.

<img width="780" alt="Screenshot 2020-02-05 at 10 11 05" src="https://user-images.githubusercontent.com/5583681/73827435-d42a5c80-47ff-11ea-9ebb-5fc7bdd7ba96.png">

Fluor doesn't impact per-key mapping it just switches between one mode to another. If per-key mapping is what you are looking for I'd suggest you taking a look at [Karabiner-Elements](https://pqrs.org/osx/karabiner/). You can use it alongside Fluor.

Hope it helps 😃 
Regards,

**Comment by hvt2** [comment]
Thank so much!
