### ISSUE TITLE
Does it work with the Touchbar ?

### ISSUE THREAD

**Issue by sseidenthal** [Pyroh/Fluor#5]

**Comment by sseidenthal** [comment]
Is it supposed to work with the MacBook Pro's Touchbar ?

**Comment by steveoh** [comment]
I installed it and it is not doing what I had hoped it would which is active the function keys on the touchbar when certain windows are active.

**Comment by sseidenthal** [comment]
I tried also in the meantime, you are right. It would be awesome to have this feature.
