### ISSUE TITLE
Fluor does not work with Logitech keyboards

### ISSUE THREAD

**Issue by flypenguin** [Pyroh/Fluor#51]
Reproduce: 
- Use Logitech MX keys keyboard, with logi options software enabled
- switch to "fn" for pycharm (or default mode, does not matter)

expected result: 
- pressing "F*" in pycharm triggers the actual pycharm function

actual result:
- whatever is configured for the key in logi options, for example "show desktop"

**Comment by Pyroh** [comment]
Fluor only supports Apple keyboards. 
Logitech keyboards support is not planned but can be added by someone else since it’s an open source project 😃

**Comment by flypenguin** [comment]
well actually CANT cause the source code is not up to date ...

**Comment by Pyroh** [comment]
You can, code version is ahead of deployed version.
The new version will be deployed when I got time it may include your fix if you implement it 😉.

**Comment by flypenguin** [comment]
hm, i might try - although i have no clue about mac ... "systems" (?!?) programming.

**Comment by Kobe** [comment]
@Pyroh may I ask you to provide a how to (add support other keyboards)?!
