### ISSUE TITLE
brew installer

### ISSUE THREAD

**Issue by cake03** [Pyroh/Fluor#55]

**Comment by BartmanEH** [comment]
spelling typo?
`brew install --cask fluor`

**Comment by gl-Gho** [comment]
I was just telling it's ```brew install --cask fluor``` and not ```brew cask install fluor```

**Comment by bruno-robert** [comment]
I think what @gl-Gho is trying to say is that there is a typo in the readme, it should be `brew install --cask fluor` instead of `brew cask install fluor`

**Comment by gl-Gho** [comment]
Yes, so someone please fork it and make a pull request, however you do it.

**Comment by gl-Gho** [comment]
Yes, so someone please _Fork_ it and make a _Pull request_, however you do it.
