### ISSUE TITLE
What is the trigger option?

### ISSUE THREAD

**Issue by djeikyb** [Pyroh/Fluor#58]
I installed fluor 2.5.0 build 2343 on macos big sur and I see a new option labeled "Trigger"; what does it mean?

![image](https://user-images.githubusercontent.com/794743/116973730-d0d78800-ac71-11eb-945b-ef865b5458e1.png)

**Comment by Pyroh** [comment]
Hello,

The *Trigger* segments work this way :

1. The keyboard mode change is triggered only when the active app changes. This is the default behavior.
2. Also triggers the keyboard mode change with the active app change. But pressing the *fn* key will set the rule for the active app. Each *fn* key press will loop-cycle the rule for the active app in this order *same as default* -> *function keys* -> *media keys*. 
3. Only the *fn* key changes the keyboard mode globally. You cannot set per-app rules anymore. The rules are conserved for when you'll change the trigger method.

You can set how much time Fluor waits between the *fn* key being pressed and then released to consider it a key press. To do this go to *Preferences* > *Advanced* and change the *Fn key release maximum delay* value to something that suits you well. 280 ms is the default value and it's been set after some tests.  
This option merely exists for accessibility reasons.

![CleanShot 2021-05-05 at 10 54 32@2x](https://user-images.githubusercontent.com/5583681/117118161-bcd67800-ad90-11eb-8e1e-1a38ac6b44c0.png)

**Comment by djeikyb** [comment]
Thanks so much for the detailed explanation!
