### ISSUE TITLE
What does the 3 toggles under Trigger section mean? 

### ISSUE THREAD

**Issue by ashokrajab** [Pyroh/Fluor#80]
I suppose the 1st toggle with the double arrow means, the F-Keys behaviour change should be triggered when the current app changes (correct me if I'm wrong). I have no idea what the other two toggles mean. Capturing this as a tool-tip for the toggles will be helpful or at the least mentioning this in the ReadMe will help to understand the feature.
  
![image](https://user-images.githubusercontent.com/13289422/186577116-89088258-2375-44bb-990e-ea72d2e58381.png)

Thank you for building this app.

**Comment by qoomon** [comment]
@ashokrajab 
* `left button` - no special function just toggle based on active application setting (`Default mode`, `☼`, `fn` )
* `middle button` - use `🌐 fn`-key to toggle `Application mode` ( `☼` or `fn` )
* `right button` - use `🌐 fn`-key to toggle `Default mode` ( `☼` or `fn` )

**Comment by metalim** [comment]
what are the images though?
* left depicts 2 states you can toggle, that's ok.
* middle is a switch? or is it app window?
* right one looks like Eject? Huh?

**Comment by yuriipavlov** [comment]
Thanks guys! Very helpful.
Another question, is it possible to change shortcut? 
Because now it conflicts with language switching, im trying to switch language and this trigger works too.
