### ISSUE TITLE
App Window Not Opening

### ISSUE THREAD

**Issue by JimmithyWeav** [Pyroh/Fluor#94]
I had the Intel Fluor running and I found that there was an Apple Silicon Version. So i uninstalled and updated to the newest. Now the fluor app doesn't open a window when the app is clicked on. I have it set to silently run int he background (so no menubar icon or anything). The app itself is running per activity monitor but no window to make changes to the app is appearing. its still working as per the last settings because I have it set to use the F keys while I am inside Citrix Viewer. I would like to open and make changes to the app though.
![Screenshot 2024-03-04 at 8 30 58 AM](https://github.com/Pyroh/Fluor/assets/146760436/98069c47-ddb1-4e4a-8543-810e884f24cb)

**Comment by dkseatgeek** [comment]
@JimmithyWeav did you find a solution for this? I am seeing the same thing.
